//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection_Logs
    {
        public int Log_id { get; set; }
        public int Request_id { get; set; }
        public int Employee_id { get; set; }
        public System.DateTime Collection_date { get; set; }
        public Nullable<System.DateTime> Distribution_date { get; set; }
        public string Distribution_status { get; set; }
    
        public virtual Collect_Requests Collect_Requests { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
