//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zerohunger101Entities : DbContext
    {
        public Zerohunger101Entities()
            : base("name=Zerohunger101Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collect_Requests> Collect_Requests { get; set; }
        public virtual DbSet<Collection_Logs> Collection_Logs { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Food_Items> Food_Items { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
